In [1]:
import pandas as pd
import numpy as np
#https://archive.ics.uci.edu/ml/datasets/Cardiotocography

In [13]:
df = pd.read_csv("cardiotocography_done.csv")

In [14]:
df

,b,e,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,...,B,C,D,E,AD,DE,LD,FS,SUSP,Target
0,240,357,120,120,0,0,0,73,0.5,43,...,0,0,0,0,0,0,0,1,0,2
1,5,632,132,132,4,0,4,17,2.1,0,...,0,0,0,0,1,0,0,0,0,1
2,177,779,133,133,2,0,5,16,2.1,0,...,0,0,0,0,1,0,0,0,0,1
3,411,1192,134,134,2,0,6,16,2.4,0,...,0,0,0,0,1,0,0,0,0,1
4,533,1147,132,132,4,0,5,16,2.4,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,2059,2867,140,140,0,0,6,79,0.2,25,...,0,0,0,1,0,0,0,0,0,2
2122,1576,2867,140,140,1,0,9,78,0.4,22,...,0,0,0,1,0,0,0,0,0,2
2123,1576,2596,140,140,1,0,7,79,0.4,20,...,0,0,0,1,0,0,0,0,0,2
2124,1576,3049,140,140,1,0,9,78,0.4,27,...,0,0,0,1,0,0,0,0,0,2
2125,2796,3415,142,142,1,1,5,74,0.4,36,...,0,0,0,0,0,0,0,0,0,1

In [16]:
df.isnull().sum(0)

b           0
e           0
LBE         0
LB          0
AC          0
FM          0
UC          0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
DL          0
DS          0
DP          0
DR          0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
Target      0
dtype: int64