In [1]:
import pandas as pd
import numpy as np

#https://archive.ics.uci.edu/ml/datasets/Bach+Choral+Harmony

In [2]:
df=pd.read_csv("jsbach_chorals_harmony_done.csv")

In [3]:
df

,Event number,Pitch class 3,Pitch class 4,Pitch class 5,Pitch class 6,Pitch class 7,Pitch class 8,Pitch class 9,Pitch class 10,Pitch class 11,Pitch class 12,Pitch class 13,Pitch class 14,Bass,Meter,Target
0,2,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M
1,3,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M
2,4,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
3,5,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M
4,6,NO,NO,YES,NO,NO,YES,NO,NO,NO,YES,NO,NO,D,4,D_m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5659,105,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m
5660,106,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m
5661,107,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M
5662,108,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M
5663,109,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M

In [9]:
df.isnull().sum(0)

Event number      0
Pitch class 3     0
Pitch class 4     0
Pitch class 5     0
Pitch class 6     0
Pitch class 7     0
Pitch class 8     0
Pitch class 9     0
Pitch class 10    0
Pitch class 11    0
Pitch class 12    0
Pitch class 13    0
Pitch class 14    0
Bass              0
Meter             0
Target            0
dtype: int64